[General]
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,127.0.0.1
dns-server = 223.5.5.5,119.29.29.29

[Proxy]
VMess = vmess, 8.163.79.215, 10086, username=726c527c-67c3-449c-b0fa-2630866e44b7, method=auto
Shadowsocks = ss, 8.163.79.215, 8388, encrypt-method=aes-256-gcm, password=Aa123456
Hysteria2 = hysteria2, 8.163.79.215, 443, password=MyPassword123, skip-cert-verify=true, sni=bing.com

[Proxy Group]
音乐代理 = select, VMess, Shadowsocks, Hysteria2

[Rule]
# QQ音乐
DOMAIN-SUFFIX,y.qq.com,音乐代理
DOMAIN-SUFFIX,qqmusic.qq.com,音乐代理
DOMAIN-SUFFIX,music.qq.com,音乐代理
DOMAIN-SUFFIX,aqqmusic.net,音乐代理
DOMAIN-SUFFIX,qqmusic.com,音乐代理
DOMAIN-SUFFIX,i.gtimg.cn,音乐代理
DOMAIN-SUFFIX,musicc.qq.com,音乐代理
DOMAIN-SUFFIX,mobileoc.music.tc.qq.com,音乐代理
DOMAIN-SUFFIX,dl.stream.qqmusic.qq.com,音乐代理

# 全民K歌
DOMAIN-SUFFIX,kg.qq.com,音乐代理
DOMAIN-SUFFIX,kgimg.qq.com,音乐代理
DOMAIN-SUFFIX,karaoke.qq.com,音乐代理
DOMAIN-SUFFIX,kgmusic.qq.com,音乐代理
DOMAIN-SUFFIX,kgtrack.qq.com,音乐代理
DOMAIN-SUFFIX,kg.tencentcs.com,音乐代理

# 其他流量直连
FINAL,DIRECT